CXX = g++
CXXFLAGS = -Wall

student1: Student.cpp Professor.cpp Person.cpp driver.cpp
	$(CXX) $(CXXFLAGS) Student.o Person.cpp driver.cpp Professor.o -o student1

##Professor.o: Person.cpp Professor.cpp
##	$(CXX) $(CXXFLAGS) -c Professor.cpp

##Student.o: Person.cpp Student.cpp
##	$(CXX) $(CXXFLAGS) -c Student.cpp
